{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_class.TestClass object at 0x111280640>\n\n    def test_two(self):\n        x = \"hello\";\n>       assert  hasattr(x,\"check\");\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_class.py:22: AssertionError"}, "start": 1610631584776, "stop": 1610631584776, "uuid": "30a400a7-86bd-4bf5-96c3-cf3742a1614f", "historyId": "cca081f1c320efa44fffe5d884236360", "testCaseId": "9e2269e6af13cd7747e18ca37f3d74ba", "fullName": "test_class.TestClass#test_two", "labels": [{"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_class"}]}