{"name": "test_fun", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == function_fixture\n +  where 4 = fun(1)", "trace": "@pytest.mark.usefixtures(\"function_fixture\")\n    def test_fun():\n        print(\"=====我是测试函数========\");\n>       assert fun(1)==function_fixture;\nE       assert 4 == function_fixture\nE        +  where 4 = fun(1)\n\ntest_case.py:48: AssertionError"}, "attachments": [{"name": "stdout", "source": "a9ce8ba0-df2d-4e9d-a5e8-e06dbfae54af-attachment.txt", "type": "text/plain"}], "start": 1610630976903, "stop": 1610630976904, "uuid": "38e5235d-4563-46a1-b593-c118346cb93f", "historyId": "6f53166915c3706e58b93e09ccee851b", "testCaseId": "c3bcefaea6042a2e54ad9ed25d06f512", "fullName": "test_case#test_fun", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('function_fixture')"}, {"name": "suite", "value": "test_case"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28074-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case"}]}