{"name": "test01_fun", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = fun(3)", "trace": "def test01_fun():\n>       assert fun(3)==5;\nE       assert 4 == 5\nE        +  where 4 = fun(3)\n\ntest_sample.py:19: AssertionError"}, "start": 1610631530451, "stop": 1610631530452, "uuid": "c04b87e2-d738-425c-9706-d3595e20ec22", "historyId": "9566b1427850f896594a12ec2527d47c", "testCaseId": "84e28ec5d690cd0600994a609c1f27cd", "fullName": "test_sample#test01_fun", "labels": [{"name": "suite", "value": "test_sample"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28373-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample"}]}