{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 5", "trace": "@pytest.mark.usefixtures(\"log\")\n    def test_answer():\n>       assert 3 ==5\nE       assert 3 == 5\n\ntest_case_05.py:26: AssertionError"}, "attachments": [{"name": "stdout", "source": "ea546241-e3b2-4b9f-8810-fad8af0c7727-attachment.txt", "type": "text/plain"}], "start": 1610631193704, "stop": 1610631193705, "uuid": "1daf88ec-8e77-4bd6-91f1-aa4437033f0f", "historyId": "16b05494b686dec1392df67e90a1684a", "testCaseId": "fa6173df133eba4369274c562d195c5a", "fullName": "test_case_05#test_answer", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log')"}, {"name": "suite", "value": "test_case_05"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28222-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_05"}]}