{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 5", "trace": "@pytest.mark.usefixtures(\"log\")\n    def test_answer():\n>       assert 3 ==5\nE       assert 3 == 5\n\ntest_case_05.py:26: AssertionError"}, "start": 1610630976502, "stop": 1610630976503, "uuid": "3799377b-30bf-423e-94ff-f7fb9fcf8da1", "historyId": "16b05494b686dec1392df67e90a1684a", "testCaseId": "fa6173df133eba4369274c562d195c5a", "fullName": "test_case_05#test_answer", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log')"}, {"name": "suite", "value": "test_case_05"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28074-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_05"}]}