{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 5", "trace": "@pytest.mark.usefixtures(\"log\")\n    def test_answer():\n>       assert 3 ==5\nE       assert 3 == 5\n\ntest_case_05.py:26: AssertionError"}, "attachments": [{"name": "stdout", "source": "ee58c600-f00c-42c2-8ead-3784f94b5c4b-attachment.txt", "type": "text/plain"}], "start": 1610631584759, "stop": 1610631584759, "uuid": "eb2a0620-9aa4-4eb4-8861-f6e1c60887de", "historyId": "16b05494b686dec1392df67e90a1684a", "testCaseId": "fa6173df133eba4369274c562d195c5a", "fullName": "test_case_05#test_answer", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log')"}, {"name": "suite", "value": "test_case_05"}, {"name": "host", "value": "yantianpeng.local"}, {"name": "thread", "value": "28416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_05"}]}